apiVersion: v1
kind: Secret
metadata:
  name: kaniko-secret
stringData:
  config.json: |-
    {
        "auths": {
            "${REGISTRY_NAME}.azurecr.io": {
                "identitytoken": "${token}"
            }
        }
    }