apiVersion: v1
kind: Secret
metadata:
  name: kaniko-secret
stringData:
  config.json: |-
    {
        "auths": {
            "azureacrgirish.azurecr.io": {
                "identitytoken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkVERFE6SFVYWDpMQzQ3OlpCUk06T0k0WTpPUjY2OkFVWko6Qlk3RTo3N0pWOjU0UlI6UU1BSzpOTDI1In0.eyJqdGkiOiJiZDQ3MmJhYS1iZjMyLTQ0MDEtOTVlZi1kYjFiOTM4ZmUyMWUiLCJzdWIiOiJHaXJpc2hnb3VkYS5Hb3VkYXIxQGdkcy5leS5jb20iLCJuYmYiOjE2MzA3Njg3ODEsImV4cCI6MTYzMDc4MDQ4MSwiaWF0IjoxNjMwNzY4NzgxLCJpc3MiOiJBenVyZSBDb250YWluZXIgUmVnaXN0cnkiLCJhdWQiOiJhenVyZWFjcmdpcmlzaC5henVyZWNyLmlvIiwidmVyc2lvbiI6IjEuMCIsInJpZCI6ImI3ZTFjOTllNjBkMDQ3MWU4OTZiNDBjZWE5NmQwNDVjIiwiZ3JhbnRfdHlwZSI6InJlZnJlc2hfdG9rZW4iLCJhcHBpZCI6IjA0YjA3Nzk1LThkZGItNDYxYS1iYmVlLTAyZjllMWJmN2I0NiIsInRlbmFudCI6IjViOTczZjk5LTc3ZGYtNGJlYi1iMjdkLWFhMGM3MGI4NDgyYyIsInBlcm1pc3Npb25zIjp7IkFjdGlvbnMiOlsicmVhZCIsIndyaXRlIiwiZGVsZXRlIl0sIk5vdEFjdGlvbnMiOm51bGx9LCJyb2xlcyI6W119.a1skXHDU6xZXrZBHNjoJke_JEZeNTc0xyJ_ouixT6WeNGo66b94KOQaoXFQM8_ZwU8x8vf9TYnq_MpALivtwdoCOLT2C80JM5CuRTqaDAlIguoCWANIKcmwnOcpwH7mAR3buab_xCs0ykXGBIa3Qf9Vnc92cG8WgSaajfe8VkqMKWHbrJ72WKd04YnE5NLqQbyv2NmbBBEyC5hZtyk3TXjChFSQZNLzp1tPYnCyF4RxqQg0SjfKeQW5fbMnnmQfKjMVJY62Irf6RW38UsHICky32Z9f1ny2jTzaj7MxJKyaO1wPP3sn_ONVv1qz1H6HzKtSNfhkgfpwtR75nd5Eg"
            }
        }
    }